
management:
    security:
        enabled: false
security:
    basic:
        enabled: false
 
spring:
    profiles:
      active: "prod"
    data:
      rest:
        base-path: /api/data
    output:
        ansi:
            enabled: DETECT
    application:
        name: DevPointSystem
    batch:
        job:
            enabled: false        
 
    jmx.enabled: true
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        url: jdbc:sqlserver://localhost\sql2019;database=MasterDev;integratedSecurity=false;encrypt=false;trustServerCertificate=true
        username: sa
        password: 123 

        
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
            use_sql_comments : true
            show-sql: true
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.default_schema: PARAM
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            org.hibernate.envers.store_data_at_delete: true
 
#                   
    messages:
        basename: i18n/messages
     
lang:
    secondary: ar
server:
    port: 9000
    contextPath: /parametrage-core
    error:
        include-stacktrace: ON_PARAM
 
environnement : local
 
 
# 
#spring:
#  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost\sql2019;database=MasterDev;integratedSecurity=false;encrypt=false;trustServerCertificate=true
#    username: sa
#    password: 123
#  jpa:
#    show-sql: false
#    generate-ddl: true
#
#
#
#
#lang:
#  secondary: ar
#
#  hibernate:
#    dialect: org.hibernate.dialect.SQLServer2012Dialect
#    format_sql : true
#    ddl-auto : update
#    show_sql: true
#    use_sql_comments : true
#
#
##logging:
##  level:
##    org:
##      hibernate:
##        type: trace
##    connection:
##      characterEncoding:utf-8
##      CharSet:utf-8
##      useUnicode:true
#
#
#
#
#  data:
#    rest:
#      base-path: /api/data
##  http:
##    encoding:
##      charset: UTF-8
##      enabled: true
##      force : true
#paramAchatService :
#  base-uri : http://localhost:8080/api/parametrage/
#  #    base-uri : http://172.20.102.26/parametrage-achat-core
#  #    base-uri : http://172.20.18.26/parametrage-achat-core
##  catArticle: /api/Filiale
#  religion : /api/Filiale
#
#
#
#server:
#  error:
#    include-stacktrace: ON_PARAM
#  port : 8081
##  tomcat:
##    uri-encoding:UTF-8
#
#
#
##web:
##  cors:
##    allowed-origins: "http://localhost:4200"
##    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
###    allowed-Headers: Origin,Access-Control-Allow-Origin, Content-Type,Accept, Authorization,Origin, Accept,X-Requested-With,Access-Control-Request-Method,Access-Control-Request-Headers
###    Exposed-Headers: Origin,Content-Type,Accept,Authorization,Access-Control-Allow-Origin,Access-Control-Allow-Credentials
##
###    max-age: 3600
###    allowed-headers: "Requestor-Type"
###    exposed-headers: "X-Get-Header"
##    changeOrigin": false